package uk.gov.hmcts.reform.sandl.snlrules.rules

import uk.gov.hmcts.reform.sandl.snlrules.model.Session;
import uk.gov.hmcts.reform.sandl.snlrules.model.Judge;
import uk.gov.hmcts.reform.sandl.snlrules.model.Availability;
import uk.gov.hmcts.reform.sandl.snlrules.model.Problem;

rule "Failing rule"
    when
    	Session()
    then
        System.out.println("Failing problem");
        insertLogical(new Problem("I1", "Fail2"));
end




